name: SFApp
options:
  bundleIdPrefix: com.yoyulyvw
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
targets:
  SFApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    info:
      path: Sources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yoyulyvw.sfapp
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        ENABLE_BITCODE: "NO"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        GENERATE_INFOPLIST_FILE: "NO"
